name: $(BuildID).$(Date:yyyyMMdd).$(SourceBranchName)

trigger:
  branches:
    include:
      # in order as per GitFlow Branching strategy
      - 'main'
      - 'hotfix/*'
      - 'release/*'
      - 'develop'
      - 'feature/*'
      - 'epic/*'
      - 'gh-readonly-queue/*'
  paths:
    exclude:
      - '.github/**'
pr:
  branches:
    include:
      - 'main'
      - 'develop'
  paths:
    exclude:
      - '.github/**'

resources:
  repositories:
    - repository: MMOPipelineCommon
      name: 'DEFRA/eutd-mmo-fes-pipeline-common'
      endpoint: DEFRA
      type: github
      ref: refs/heads/main

stages:
  - template: /includes/npm-package-build-publish.yaml@MMOPipelineCommon
